databases:
  - name: footballdb
    plan: free
    databaseName: football
    user: football

services:
  - type: web
    plan: free
    name: football
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn football.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: footballdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4