# Generated by Django 4.2.3 on 2024-09-11 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('other_name', models.CharField(blank=True, max_length=500)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': "Player's Nationalities",
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, null=True)),
                ('league', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament', to='app.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text="Player's age at this particular season")),
                ('match_played', models.PositiveIntegerField()),
                ('starts', models.PositiveIntegerField(help_text='Total number of matches started')),
                ('minutes_played', models.PositiveIntegerField()),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('card_yellow', models.PositiveIntegerField()),
                ('card_red', models.PositiveIntegerField()),
                ('penalty', models.PositiveIntegerField(help_text='Total number of penalties scored')),
                ('goals_assist', models.PositiveIntegerField(help_text='Total number of goals and assits')),
                ('goals_penalty', models.PositiveIntegerField(help_text='Total number of penalties and goals')),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.team')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
                ('position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.position')),
                ('season', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.season')),
            ],
            options={
                'ordering': ['-goals'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.playernationality'),
        ),
        migrations.AddField(
            model_name='player',
            name='year_of_birth',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.birthyear'),
        ),
        migrations.CreateModel(
            name='MatchDayScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('match_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='app.team'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='app.team'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='touranment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournament'),
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
                ('credit', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, null=True)),
                ('subscription', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50, null=True)),
                ('expiry_date', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('point', models.PositiveIntegerField(blank=True, null=True)),
                ('total_point', models.PositiveIntegerField(blank=True, null=True)),
                ('ground', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('Neutral', 'Neutral')], max_length=50)),
                ('outcome', models.CharField(choices=[('W', 'Win'), ('D', 'Draw'), ('L', 'Lose')], max_length=10)),
                ('matchweek', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38)], null=True)),
                ('goals_scored', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_against', models.PositiveIntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club', to='app.team')),
                ('club_against', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Club_against', to='app.team')),
                ('season', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.season')),
                ('tournament', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_tournament', to='app.tournament')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
